baseUrl:       https://deniskramer.github.io/documental

github:
  url:         https://github.com/DenisKramer/documental
  branch:      jekyll

title:         Documental
description:   An elegant template for documentation using Couscous                        My wonderful software does fantastic things


header:
  items:
    - text:    Getting started
      url:     getting-started.html
    - text:    Documentation
      url:     documentation.html

menu:
  items:
    - section: Usage
      items:
        - text: Getting started
          url: getting-started.html
        - text: Template configuration
          url: documentation.html

    - section: Development
      items:
        - text: Build environment
          url: build.html
