baseUrl:                 https://deniskramer.github.io/documental
githubUrl:               https://github.com/DenisKramer/documental

title:                   Documental
description:             An elegant template for documentation using Couscous                        My wonderful software does fantastic things


header:
  items:
    - text:              Getting started
      url:               getting-started.html
    - text:              Documentation
      url:               documentation.html

menu:
  items:
    usage:
      section:           Usage
      items:
        getting-started:
          text:          Getting started
          url:           getting-started.html
        configuration:
          text:          Template configuration
          url:           documentation.html

    development:
      section:           Development
      items:
        build:
          text:          Build environment
          url:           build.html
